# Generated by Django 5.0.2 on 2024-02-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_types',
            name='speed',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
