# Generated by Django 5.0.2 on 2024-02-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_cpu_types_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_types',
            name='speed',
            field=models.CharField(max_length=15),
        ),
    ]
