# Generated by Django 5.0.2 on 2024-02-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_cpu_types_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard_type',
            name='brand',
        ),
    ]
