# Generated by Django 5.0.2 on 2024-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0004_remove_motherboard_type_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computers",
            name="status",
            field=models.CharField(
                choices=[("working", "working"), ("not working", "not working")],
                max_length=20,
            ),
        ),
    ]
