# Generated by Django 5.0.2 on 2024-06-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_alter_computers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.keyboard'),
        ),
    ]
